services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # HTTP port
      - "5000:5000"  # WebSocket port
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db
      #- ./logs:/app/logs
    environment:
      - MONGO_LOG_LEVEL=1

volumes:
  mongo_data:
    driver: local
